import nodemailer from 'nodemailer';
import { logger, level } from '../config/logger';
import { constants as EMAIL_CONST } from '../constant/email';
const HOST = EMAIL_CONST.HOST;
const PORT = EMAIL_CONST.PORT;
const USER = EMAIL_CONST.USER;
const PASS = EMAIL_CONST.PASS;

var transport = nodemailer.createTransport({
  pool: true,
  host: HOST,
  port: PORT,
  secure: false,
  auth: {
    user: USER, //example of generated by Mailtrap
    pass: PASS //example of generated by Mailtrap
  },
  tls: {
    // do not fail on invalid certs
    rejectUnauthorized: false
  }
});

transport.verify((error, _success) => {
  if (error) {
    logger.log(level.error, error);
  } else {
    logger.log(level.info, 'Server is ready to take our messages');
  }
});

export default transport;
